import { lang } from "../lib/i18n";

const COPY = {
  de: {
    furry: "Fell",
    jelly: "Jelly",
    both: "Vergleichen",
    material: "Material",
    clarity: "Transparenz",
    softness: "Weichheit",
    jellyHint: "Jelly ziehen und loslassen, um das elastische Nachfedern zu sehen.",
    background: "Hintergrund",
    light: "Hell",
    match: "Passend zur Figur",
    palette: "Dunkle Engenty-Farben",
    play: "Abspielen",
    pause: "Pause",
    speed: "Tempo",
    motionHint:
      "Automatisch gemäß Systemeinstellung. Abspielen aktiviert die Vorschau auch bei reduzierter Bewegung.",
    angle: "Drehwinkel (°)",
    tilt: "Neigung (°)",
    fur: "Felllänge",
    density: "Haardichte",
    thick: "Haarstärke",
    inflate: "Körperwölbung",
    wind: "Wind",
    description:
      "Fell und Jelly vergleichen, in Bewegung ansehen und auf ihren Bühnenfarben abstimmen.",
    back: "Zurück zu Wizards",
    preview: "Vorschau",
    dark: "Dunkler Hintergrund",
    follow: "Blick folgt Maus",
    goggles: "Pilotenbrille",
    controls: "Renderer einstellen",
    form: "Form",
    reset: "Zurücksetzen",
    gallery: "Alle Formen · kleine Darstellung",
  },
  en: {
    furry: "Fur",
    jelly: "Jelly",
    both: "Compare",
    material: "Material",
    clarity: "Transparency",
    softness: "Softness",
    jellyHint: "Drag and release the Jelly to see it spring back.",
    background: "Background",
    light: "Light",
    match: "Match character",
    palette: "Dark Engenty colours",
    play: "Play",
    pause: "Pause",
    speed: "Speed",
    motionHint:
      "Automatic playback follows your system setting. Play explicitly enables animation, including with reduced motion.",
    angle: "Turn angle (°)",
    tilt: "Tilt (°)",
    fur: "Fur length",
    density: "Hair density",
    thick: "Hair width",
    inflate: "Body volume",
    wind: "Wind",
    description: "Compare fur and jelly in motion, and tune them against their stage colours.",
    back: "Back to Wizards",
    preview: "Preview",
    dark: "Dark background",
    follow: "Follow pointer",
    goggles: "Pilot goggles",
    controls: "Renderer controls",
    form: "Shape",
    reset: "Reset",
    gallery: "All shapes · small sizes",
  },
} as const;

type Copy = (typeof COPY)[keyof typeof COPY];

/** The copy in the language in effect, looked up on every read: the language can change. */
export const builderCopy = new Proxy({} as Copy, {
  get: (_target, key) => COPY[lang][key as keyof Copy],
});
