import type { StarterListing } from "./types.js";

/**
 * The base set's place in the marketplace, by starter id. A starter that changes gets its
 * `revision` raised here; a new starter gets a line.
 */
export const STARTER_LISTINGS: Record<string, StarterListing> = {
  tweet: {
    revision: 1,
    industries: ["any"],
    useCases: ["marketing"],
    search: [
      "Tweet",
      "Twitter",
      "X",
      "Social-Media-Post",
      "Beitrag",
      "Posting",
      "LinkedIn-Post",
      "Kurztext mit Bild",
      "Ankündigung",
      "social media post",
      "announcement",
      "post with image",
      "caption",
    ],
  },
  "facebook-video-ad": {
    revision: 1,
    industries: ["retail", "agency"],
    useCases: ["marketing"],
    search: [
      "Werbevideo",
      "Werbeclip",
      "Werbespot",
      "kurzes Video",
      "Kurzvideo",
      "Reel",
      "Instagram",
      "TikTok",
      "Meta Ads",
      "Video-Ad",
      "Hochformat",
      "Produktvideo",
      "Werbung für mein Geschäft",
      "Kampagne",
      "video ad",
      "promo video",
      "short video",
      "vertical video",
      "commercial",
      "advertising",
    ],
  },
  "property-film": {
    revision: 1,
    industries: ["realEstate"],
    useCases: ["marketing"],
    search: [
      "Immobilienvideo",
      "Exposé-Video",
      "Wohnungsrundgang",
      "Hausbesichtigung",
      "virtuelles Staging",
      "Home Staging",
      "Immobilienfotos bearbeiten",
      "Makler",
      "Wohnung verkaufen",
      "Besichtigung",
      "real estate video",
      "property tour",
      "listing video",
      "virtual staging",
      "walkthrough",
    ],
  },
  "research-briefing": {
    revision: 1,
    industries: ["any"],
    useCases: ["research"],
    search: [
      "Recherche",
      "Marktrecherche",
      "Wettbewerbsanalyse",
      "Hintergrundbericht",
      "Zusammenfassung",
      "Report",
      "Quellen",
      "Thema recherchieren",
      "Entscheidungsvorlage",
      "research report",
      "market research",
      "competitor analysis",
      "summary with sources",
      "briefing",
    ],
  },
  dashboard: {
    revision: 1,
    industries: ["any"],
    useCases: ["research"],
    search: [
      "Kennzahlen",
      "Diagramme",
      "Charts",
      "Statistik",
      "Marktdaten",
      "Zahlen vergleichen",
      "Auswertung",
      "Grafik",
      "Übersicht",
      "KPI",
      "charts",
      "statistics",
      "data visualisation",
      "market figures",
      "report with graphs",
    ],
  },
  invoice: {
    revision: 1,
    industries: ["any"],
    useCases: ["accounting"],
    search: [
      "Rechnung schreiben",
      "Rechnung stellen",
      "Abrechnung",
      "Faktura",
      "Honorarnote",
      "PDF-Rechnung",
      "Kunde abrechnen",
      "Mehrwertsteuer",
      "Rechnungsnummer",
      "invoice",
      "bill",
      "billing",
      "bill a customer",
      "invoice as PDF",
    ],
  },
  offer: {
    revision: 1,
    industries: ["any"],
    useCases: ["sales"],
    search: [
      "Angebot schreiben",
      "Kostenvoranschlag",
      "Offerte",
      "Kalkulation",
      "Preisangebot",
      "Angebot als PDF",
      "Kunde anfragen",
      "Leistungen und Preise",
      "quote",
      "quotation",
      "proposal",
      "estimate",
      "offer for a customer",
    ],
  },
  damage: {
    revision: 1,
    industries: ["trades", "realEstate"],
    useCases: ["operations"],
    search: [
      "Schaden melden",
      "Schadensbericht",
      "Schadensprotokoll",
      "Versicherung",
      "Wasserschaden",
      "Mängelprotokoll",
      "Begehung",
      "Baustelle",
      "Abnahme",
      "Protokoll mit Fotos",
      "damage report",
      "incident report",
      "insurance claim",
      "site inspection",
      "defect report",
    ],
  },
  "window-offer": {
    revision: 1,
    industries: ["trades"],
    useCases: ["sales"],
    search: [
      "Fenster",
      "Türen",
      "Aufmaß",
      "Vor-Ort-Angebot",
      "Handwerker-Angebot",
      "Tischler",
      "Fensterbauer",
      "Sanierung",
      "Kostenvoranschlag vor Ort",
      "Preisliste",
      "Maße aufnehmen",
      "window replacement",
      "on-site quote",
      "tradesman quote",
      "measurements",
    ],
  },
  receipts: {
    revision: 1,
    industries: ["any"],
    useCases: ["accounting"],
    search: [
      "Buchhaltung",
      "Belege sammeln",
      "Belege zuordnen",
      "Steuerberater",
      "Monatsabschluss",
      "Kontoauszug",
      "Rechnungen suchen",
      "fehlende Belege",
      "Quittungen",
      "Spesen",
      "bookkeeping",
      "receipts",
      "expenses",
      "bank statement",
      "tax advisor",
      "month-end",
    ],
  },
  "menu-plan": {
    revision: 1,
    industries: ["gastronomy", "publicSector"],
    useCases: ["operations"],
    search: [
      "Speiseplan",
      "Essensplan",
      "Menüplan",
      "Wochenplan",
      "Kantine",
      "Kita",
      "Schule",
      "Mittagessen",
      "Küche",
      "Einkaufsliste",
      "Rezepte planen",
      "meal plan",
      "weekly menu",
      "canteen",
      "shopping list",
      "lunch plan",
    ],
  },
  "web-faq": {
    revision: 1,
    industries: ["health"],
    useCases: ["website", "service"],
    search: [
      "FAQ",
      "Fragen beantworten",
      "Chatbot",
      "Kundenfragen",
      "Auskunft",
      "Hilfe auf der Website",
      "Praxis",
      "Öffnungszeiten",
      "häufige Fragen",
      "Support",
      "questions and answers",
      "help widget",
      "customer questions",
      "website assistant",
    ],
  },
  "web-price": {
    revision: 1,
    industries: ["trades"],
    useCases: ["website", "sales"],
    search: [
      "Preisrechner",
      "Kostenrechner",
      "Preis anfragen",
      "Kostenschätzung",
      "Richtpreis",
      "Kalkulator",
      "Was kostet",
      "Preisauskunft",
      "Anfrageformular",
      "price calculator",
      "cost estimate",
      "quote calculator",
      "pricing widget",
      "lead form",
    ],
  },
  "web-advisor": {
    revision: 1,
    industries: ["retail"],
    useCases: ["website", "sales"],
    search: [
      "Kaufberatung",
      "Produktfinder",
      "Empfehlung",
      "Produktempfehlung",
      "Beratung im Shop",
      "Sortiment",
      "welches Produkt passt",
      "Geschenkfinder",
      "product finder",
      "product recommendation",
      "shopping advisor",
      "quiz",
      "guided selling",
    ],
  },
  "web-appointment": {
    revision: 1,
    industries: ["professional"],
    useCases: ["website", "service"],
    search: [
      "Erstgespräch",
      "Termin",
      "Beratungstermin",
      "Mandant",
      "Unterlagen",
      "Checkliste",
      "Vorbereitung",
      "Kanzlei",
      "Steuerberater",
      "Anwalt",
      "Anliegen schildern",
      "appointment",
      "intake form",
      "first meeting",
      "checklist",
      "client onboarding",
    ],
  },
  "web-complaint": {
    revision: 1,
    industries: ["retail"],
    useCases: ["website", "service"],
    search: [
      "Reklamation",
      "Beschwerde",
      "Rückgabe",
      "Retoure",
      "Umtausch",
      "Garantie",
      "defekte Ware",
      "Bestellung reklamieren",
      "Kundendienst",
      "complaint",
      "return",
      "refund",
      "warranty claim",
      "damaged order",
      "customer service",
    ],
  },
  "web-application": {
    revision: 1,
    industries: ["any"],
    useCases: ["website", "hr"],
    search: [
      "Bewerbung",
      "Jobs",
      "Stellenanzeige",
      "Recruiting",
      "Karriere",
      "Bewerber",
      "Lebenslauf",
      "Personal suchen",
      "schnell bewerben",
      "Mitarbeiter finden",
      "job application",
      "apply",
      "CV",
      "resume",
      "hiring",
      "careers page",
    ],
  },
  "web-event": {
    revision: 1,
    industries: ["gastronomy", "events"],
    useCases: ["website", "sales"],
    search: [
      "Feier",
      "Veranstaltung",
      "Hochzeit",
      "Geburtstag",
      "Firmenfeier",
      "Weihnachtsfeier",
      "Catering",
      "Raum mieten",
      "Location",
      "Gruppenreservierung",
      "Eventanfrage",
      "event request",
      "party",
      "wedding",
      "venue",
      "group booking",
      "catering",
    ],
  },
  "web-dayplan": {
    revision: 1,
    industries: ["hospitality"],
    useCases: ["website", "service"],
    search: [
      "Ausflug",
      "Urlaub",
      "Tagesprogramm",
      "Ausflugstipps",
      "Gäste",
      "Hotel",
      "Tourismus",
      "Region",
      "Sehenswürdigkeiten",
      "Wetter",
      "Aktivitäten",
      "was tun heute",
      "day plan",
      "itinerary",
      "things to do",
      "trip",
      "hotel guests",
      "tourism",
    ],
  },
  "web-sitecheck": {
    revision: 1,
    industries: ["agency"],
    useCases: ["website", "marketing"],
    search: [
      "Website-Analyse",
      "SEO-Check",
      "Homepage prüfen",
      "Website-Audit",
      "Verbesserungen",
      "Leadmagnet",
      "Agentur",
      "Webseite testen",
      "Ladezeit",
      "website audit",
      "SEO check",
      "site review",
      "lead magnet",
      "homepage analysis",
    ],
  },
  "web-funding": {
    revision: 1,
    industries: ["trades", "professional"],
    useCases: ["website", "sales"],
    search: [
      "Förderung",
      "Fördermittel",
      "Zuschuss",
      "Subvention",
      "Heizungstausch",
      "Wärmepumpe",
      "Photovoltaik",
      "Sanierung",
      "Energieberatung",
      "Förderprogramm",
      "funding",
      "grants",
      "subsidies",
      "heat pump",
      "solar",
      "energy renovation",
    ],
  },
};
